version: 2

jobs:
  build-and-test:
    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: output
    macos:
      xcode: "11.2.1"
    working_directory: ~/VimeoNetworking
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}

      - run:
          name: Set Ruby version
          command: echo "ruby-2.4" > ~/.ruby-version

      - run:
          name: Install bundler dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec fastlane test

      - run:
          name: Carthage build
          command: carthage build --no-skip-current --no-use-binaries

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-gems-{{ checksum "Gemfile.lock" }}

      - store_artifacts:
          path: output

      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
